### ISSUE TITLE
Test failure when building rulewerk

### ISSUE THREAD

**Issue by mrnolte** [knowsys/rulewerk#168]
Hey there,
Due to the bug karmaresearch/vlog#43 being fixed, I tried to build the latest rulewerk snapshot locally using the provided script and maven install.
Unfortunately, the tests during the build process of Core Components did fail:
```
[INFO] Running org.semanticweb.rulewerk.core.reasoner.vlog.StratifiedNegationTest
HEAD: [R[VARIABLE: x]], BODY: [P[VARIABLE: x], ~Q[VARIABLE: x]]
HEAD: [R[VARIABLE: x]], BODY: [P[VARIABLE: x], ~Q[VARIABLE: x]]
[ERROR] Tests run: 3, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.238 s <<< FAILURE! - in org.semanticweb.rulewerk.core.reasoner.vlog.StratifiedNegationTest
[ERROR] org.semanticweb.rulewerk.core.reasoner.vlog.StratifiedNegationTest.testSimpleInputNegation  Time elapsed: 0.18 s  <<< FAILURE!
org.junit.internal.ArrayComparisonFailure: arrays first differed at element [0]; expected:<CONSTANT: c> but was:<CONSTANT: d>
	at org.semanticweb.rulewerk.core.reasoner.vlog.StratifiedNegationTest.testSimpleInputNegation(StratifiedNegationTest.java:98)
Caused by: java.lang.AssertionError: expected:<CONSTANT: c> but was:<CONSTANT: d>
	at org.semanticweb.rulewerk.core.reasoner.vlog.StratifiedNegationTest.testSimpleInputNegation(StratifiedNegationTest.java:98)

[ERROR] org.semanticweb.rulewerk.core.reasoner.vlog.StratifiedNegationTest.testStratifiedNegationOnIDB  Time elapsed: 0.017 s  <<< FAILURE!
java.lang.AssertionError
	at org.semanticweb.rulewerk.core.reasoner.vlog.StratifiedNegationTest.testStratifiedNegationOnIDB(StratifiedNegationTest.java:145)
```
I did take a quick look into `testSimpleInputNegation` and to me it seems to be another VLog bug (?).

Cheers,
Robin

**Comment by mmarx** [comment]
Thanks, I have forwarded it as karmaresearch/vlog#44.

**Comment by mmarx** [comment]
This should be fixed now, could you please try again?

**Comment by mrnolte** [comment]
Great, the build succeeds now.
Thank you very much!
