### ISSUE TITLE
Building rulewerk for Windows

### ISSUE THREAD

**Issue by mrnolte** [knowsys/rulewerk#169]
Hey there,
Im am very sorry to bother you again, but I have a question regarding Rulewerk for Windows.
As mentioned, I suceeded building Rulewerk 0.6.0-SNAPSHOT using the provided script.
The resulting jars work just fine on Linux,; the reported bug is indeed fixed now.
On Windows however, the following error occurs whenever I try to instantiate a `VLogReasoner`:
```
java.lang.UnsatisfiedLinkError: while loading kognac-core: Stream closed
	at karmaresearch.vlog.VLog.loadLibrary(VLog.java:76)
	at karmaresearch.vlog.VLog.<clinit>(VLog.java:23)
	at org.semanticweb.rulewerk.core.reasoner.implementation.VLogReasoner.<init>(VLogReasoner.java:82)	
```
Do I have to build VLog for Windows specifically? And if so, how do I do that?

Thank you a lot for your help so far!

Cheers,
Robin

**Comment by irina-dragoste** [comment]
I reported this issue to https://github.com/karmaresearch/vlog/issues/45.
The self-built jar is OS-dependent, therefore a jar built on a certain OS only contains the libraries required by that OS, and cannot function on another OS.
The cmake instructions in build-vlog-library.sh script only work for Linux and MacOS, this script cannot be used on Windows. I hope that karmaresearch/vlog project will soon contain instructions on how the jar can be built on Windows.

The relased jars (with artifact id vlog4j-base) contain OS-specific libraries for Windows, Linux and MacOS.
